import "./globals.css";
import { Providers } from "./provider";

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-noto">
        <Providers>

          {children}
        </Providers>
      </body>
    </html>
  );
}
