import "./globals.css";
import { Providers } from "./provider";
import SessionProvider from "../components/SessionProvider";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="font-noto">
        <Providers>
          <SessionProvider session={session}>
          {children}
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
